language: go
go_import_path: github.com/bityuan/bityuan
os: linux
dist: xenial

notifications:
  email: false
jobs:
  include:
    - stage: check_fmt
      sudo: require
      go: "1.11.x"
      install:
        - go get -u golang.org/x/tools/cmd/goimports
        - go get -u gopkg.in/alecthomas/gometalinter.v2
        - gometalinter.v2 -i
        - go get -u mvdan.cc/sh/cmd/shfmt
        - go get -u mvdan.cc/sh/cmd/gosh
      script:
        - make checkgofmt && make fmt
        - make linter


    - stage: auto-test
      go: "1.9.x"
      install: skip
      before_script: make
      script:
        - make autotest dapp=coins
        - make autotest dapp=ticket
        - make autotest dapp=hashlock
        - make autotest dapp=retrieve
        - make autotest dapp=manage
        - make autotest dapp=token
        - make autotest dapp=trade



