// Code generated by protoc-gen-go. DO NOT EDIT.
// source: unfreeze.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/33cn/chain33/types"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Unfreeze struct {
	//解冻交易ID（唯一识别码）
	UnfreezeID string `protobuf:"bytes,1,opt,name=unfreezeID,proto3" json:"unfreezeID,omitempty"`
	//开始时间
	StartTime int64 `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	//币种
	AssetExec   string `protobuf:"bytes,3,opt,name=assetExec,proto3" json:"assetExec,omitempty"`
	AssetSymbol string `protobuf:"bytes,4,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	//冻结总额
	TotalCount int64 `protobuf:"varint,5,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	//发币人地址
	Initiator string `protobuf:"bytes,6,opt,name=initiator,proto3" json:"initiator,omitempty"`
	//收币人地址
	Beneficiary string `protobuf:"bytes,7,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	//解冻剩余币数
	Remaining int64 `protobuf:"varint,8,opt,name=remaining,proto3" json:"remaining,omitempty"`
	//解冻方式（百分比；固额；递减）
	Means string `protobuf:"bytes,9,opt,name=means,proto3" json:"means,omitempty"`
	// Types that are valid to be assigned to MeansOpt:
	//	*Unfreeze_FixAmount
	//	*Unfreeze_LeftProportion
	//	*Unfreeze_DecreaseAmount
	MeansOpt   isUnfreeze_MeansOpt `protobuf_oneof:"meansOpt"`
	Terminated bool                `protobuf:"varint,20,opt,name=terminated,proto3" json:"terminated,omitempty"`
	//锁仓标签
	UnfreezeLabel string `protobuf:"bytes,21,opt,name=unfreezeLabel,proto3" json:"unfreezeLabel,omitempty"`
	//是否撤销
	IsRevoke             bool     `protobuf:"varint,22,opt,name=isRevoke,proto3" json:"isRevoke,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unfreeze) Reset()         { *m = Unfreeze{} }
func (m *Unfreeze) String() string { return proto.CompactTextString(m) }
func (*Unfreeze) ProtoMessage()    {}
func (*Unfreeze) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{0}
}

func (m *Unfreeze) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unfreeze.Unmarshal(m, b)
}
func (m *Unfreeze) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unfreeze.Marshal(b, m, deterministic)
}
func (m *Unfreeze) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unfreeze.Merge(m, src)
}
func (m *Unfreeze) XXX_Size() int {
	return xxx_messageInfo_Unfreeze.Size(m)
}
func (m *Unfreeze) XXX_DiscardUnknown() {
	xxx_messageInfo_Unfreeze.DiscardUnknown(m)
}

var xxx_messageInfo_Unfreeze proto.InternalMessageInfo

func (m *Unfreeze) GetUnfreezeID() string {
	if m != nil {
		return m.UnfreezeID
	}
	return ""
}

func (m *Unfreeze) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Unfreeze) GetAssetExec() string {
	if m != nil {
		return m.AssetExec
	}
	return ""
}

func (m *Unfreeze) GetAssetSymbol() string {
	if m != nil {
		return m.AssetSymbol
	}
	return ""
}

func (m *Unfreeze) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *Unfreeze) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *Unfreeze) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func (m *Unfreeze) GetRemaining() int64 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *Unfreeze) GetMeans() string {
	if m != nil {
		return m.Means
	}
	return ""
}

type isUnfreeze_MeansOpt interface {
	isUnfreeze_MeansOpt()
}

type Unfreeze_FixAmount struct {
	FixAmount *FixAmount `protobuf:"bytes,10,opt,name=fixAmount,proto3,oneof"`
}

type Unfreeze_LeftProportion struct {
	LeftProportion *LeftProportion `protobuf:"bytes,11,opt,name=leftProportion,proto3,oneof"`
}

type Unfreeze_DecreaseAmount struct {
	DecreaseAmount *DecreaseAmount `protobuf:"bytes,12,opt,name=decreaseAmount,proto3,oneof"`
}

func (*Unfreeze_FixAmount) isUnfreeze_MeansOpt() {}

func (*Unfreeze_LeftProportion) isUnfreeze_MeansOpt() {}

func (*Unfreeze_DecreaseAmount) isUnfreeze_MeansOpt() {}

func (m *Unfreeze) GetMeansOpt() isUnfreeze_MeansOpt {
	if m != nil {
		return m.MeansOpt
	}
	return nil
}

func (m *Unfreeze) GetFixAmount() *FixAmount {
	if x, ok := m.GetMeansOpt().(*Unfreeze_FixAmount); ok {
		return x.FixAmount
	}
	return nil
}

func (m *Unfreeze) GetLeftProportion() *LeftProportion {
	if x, ok := m.GetMeansOpt().(*Unfreeze_LeftProportion); ok {
		return x.LeftProportion
	}
	return nil
}

func (m *Unfreeze) GetDecreaseAmount() *DecreaseAmount {
	if x, ok := m.GetMeansOpt().(*Unfreeze_DecreaseAmount); ok {
		return x.DecreaseAmount
	}
	return nil
}

func (m *Unfreeze) GetTerminated() bool {
	if m != nil {
		return m.Terminated
	}
	return false
}

func (m *Unfreeze) GetUnfreezeLabel() string {
	if m != nil {
		return m.UnfreezeLabel
	}
	return ""
}

func (m *Unfreeze) GetIsRevoke() bool {
	if m != nil {
		return m.IsRevoke
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Unfreeze) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Unfreeze_OneofMarshaler, _Unfreeze_OneofUnmarshaler, _Unfreeze_OneofSizer, []interface{}{
		(*Unfreeze_FixAmount)(nil),
		(*Unfreeze_LeftProportion)(nil),
		(*Unfreeze_DecreaseAmount)(nil),
	}
}

func _Unfreeze_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Unfreeze)
	// meansOpt
	switch x := m.MeansOpt.(type) {
	case *Unfreeze_FixAmount:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FixAmount); err != nil {
			return err
		}
	case *Unfreeze_LeftProportion:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LeftProportion); err != nil {
			return err
		}
	case *Unfreeze_DecreaseAmount:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DecreaseAmount); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Unfreeze.MeansOpt has unexpected type %T", x)
	}
	return nil
}

func _Unfreeze_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Unfreeze)
	switch tag {
	case 10: // meansOpt.fixAmount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FixAmount)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &Unfreeze_FixAmount{msg}
		return true, err
	case 11: // meansOpt.leftProportion
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LeftProportion)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &Unfreeze_LeftProportion{msg}
		return true, err
	case 12: // meansOpt.decreaseAmount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DecreaseAmount)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &Unfreeze_DecreaseAmount{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Unfreeze_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Unfreeze)
	// meansOpt
	switch x := m.MeansOpt.(type) {
	case *Unfreeze_FixAmount:
		s := proto.Size(x.FixAmount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Unfreeze_LeftProportion:
		s := proto.Size(x.LeftProportion)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Unfreeze_DecreaseAmount:
		s := proto.Size(x.DecreaseAmount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 按时间固定额度解冻
type FixAmount struct {
	Period               int64    `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixAmount) Reset()         { *m = FixAmount{} }
func (m *FixAmount) String() string { return proto.CompactTextString(m) }
func (*FixAmount) ProtoMessage()    {}
func (*FixAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{1}
}

func (m *FixAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixAmount.Unmarshal(m, b)
}
func (m *FixAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixAmount.Marshal(b, m, deterministic)
}
func (m *FixAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixAmount.Merge(m, src)
}
func (m *FixAmount) XXX_Size() int {
	return xxx_messageInfo_FixAmount.Size(m)
}
func (m *FixAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_FixAmount.DiscardUnknown(m)
}

var xxx_messageInfo_FixAmount proto.InternalMessageInfo

func (m *FixAmount) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *FixAmount) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// 固定时间间隔按余量百分比解冻
type LeftProportion struct {
	Period               int64    `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	TenThousandth        int64    `protobuf:"varint,2,opt,name=tenThousandth,proto3" json:"tenThousandth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeftProportion) Reset()         { *m = LeftProportion{} }
func (m *LeftProportion) String() string { return proto.CompactTextString(m) }
func (*LeftProportion) ProtoMessage()    {}
func (*LeftProportion) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{2}
}

func (m *LeftProportion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeftProportion.Unmarshal(m, b)
}
func (m *LeftProportion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeftProportion.Marshal(b, m, deterministic)
}
func (m *LeftProportion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeftProportion.Merge(m, src)
}
func (m *LeftProportion) XXX_Size() int {
	return xxx_messageInfo_LeftProportion.Size(m)
}
func (m *LeftProportion) XXX_DiscardUnknown() {
	xxx_messageInfo_LeftProportion.DiscardUnknown(m)
}

var xxx_messageInfo_LeftProportion proto.InternalMessageInfo

func (m *LeftProportion) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *LeftProportion) GetTenThousandth() int64 {
	if m != nil {
		return m.TenThousandth
	}
	return 0
}

// 按递减比列递减周期递减次数解冻
type DecreaseAmount struct {
	Period               int64    `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	TenThousandth        int64    `protobuf:"varint,2,opt,name=tenThousandth,proto3" json:"tenThousandth,omitempty"`
	FirstDecreaseAmount  int64    `protobuf:"varint,3,opt,name=firstDecreaseAmount,proto3" json:"firstDecreaseAmount,omitempty"`
	DecreasePeriod       int64    `protobuf:"varint,4,opt,name=decreasePeriod,proto3" json:"decreasePeriod,omitempty"`
	DecreaseNums         int64    `protobuf:"varint,5,opt,name=decreaseNums,proto3" json:"decreaseNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecreaseAmount) Reset()         { *m = DecreaseAmount{} }
func (m *DecreaseAmount) String() string { return proto.CompactTextString(m) }
func (*DecreaseAmount) ProtoMessage()    {}
func (*DecreaseAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{3}
}

func (m *DecreaseAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecreaseAmount.Unmarshal(m, b)
}
func (m *DecreaseAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecreaseAmount.Marshal(b, m, deterministic)
}
func (m *DecreaseAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecreaseAmount.Merge(m, src)
}
func (m *DecreaseAmount) XXX_Size() int {
	return xxx_messageInfo_DecreaseAmount.Size(m)
}
func (m *DecreaseAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_DecreaseAmount.DiscardUnknown(m)
}

var xxx_messageInfo_DecreaseAmount proto.InternalMessageInfo

func (m *DecreaseAmount) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *DecreaseAmount) GetTenThousandth() int64 {
	if m != nil {
		return m.TenThousandth
	}
	return 0
}

func (m *DecreaseAmount) GetFirstDecreaseAmount() int64 {
	if m != nil {
		return m.FirstDecreaseAmount
	}
	return 0
}

func (m *DecreaseAmount) GetDecreasePeriod() int64 {
	if m != nil {
		return m.DecreasePeriod
	}
	return 0
}

func (m *DecreaseAmount) GetDecreaseNums() int64 {
	if m != nil {
		return m.DecreaseNums
	}
	return 0
}

// message for execs.unfreeze
type UnfreezeAction struct {
	// Types that are valid to be assigned to Value:
	//	*UnfreezeAction_Create
	//	*UnfreezeAction_Withdraw
	//	*UnfreezeAction_Terminate
	Value                isUnfreezeAction_Value `protobuf_oneof:"value"`
	Ty                   int32                  `protobuf:"varint,4,opt,name=ty,proto3" json:"ty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UnfreezeAction) Reset()         { *m = UnfreezeAction{} }
func (m *UnfreezeAction) String() string { return proto.CompactTextString(m) }
func (*UnfreezeAction) ProtoMessage()    {}
func (*UnfreezeAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{4}
}

func (m *UnfreezeAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfreezeAction.Unmarshal(m, b)
}
func (m *UnfreezeAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfreezeAction.Marshal(b, m, deterministic)
}
func (m *UnfreezeAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfreezeAction.Merge(m, src)
}
func (m *UnfreezeAction) XXX_Size() int {
	return xxx_messageInfo_UnfreezeAction.Size(m)
}
func (m *UnfreezeAction) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfreezeAction.DiscardUnknown(m)
}

var xxx_messageInfo_UnfreezeAction proto.InternalMessageInfo

type isUnfreezeAction_Value interface {
	isUnfreezeAction_Value()
}

type UnfreezeAction_Create struct {
	Create *UnfreezeCreate `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type UnfreezeAction_Withdraw struct {
	Withdraw *UnfreezeWithdraw `protobuf:"bytes,2,opt,name=withdraw,proto3,oneof"`
}

type UnfreezeAction_Terminate struct {
	Terminate *UnfreezeTerminate `protobuf:"bytes,3,opt,name=terminate,proto3,oneof"`
}

func (*UnfreezeAction_Create) isUnfreezeAction_Value() {}

func (*UnfreezeAction_Withdraw) isUnfreezeAction_Value() {}

func (*UnfreezeAction_Terminate) isUnfreezeAction_Value() {}

func (m *UnfreezeAction) GetValue() isUnfreezeAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UnfreezeAction) GetCreate() *UnfreezeCreate {
	if x, ok := m.GetValue().(*UnfreezeAction_Create); ok {
		return x.Create
	}
	return nil
}

func (m *UnfreezeAction) GetWithdraw() *UnfreezeWithdraw {
	if x, ok := m.GetValue().(*UnfreezeAction_Withdraw); ok {
		return x.Withdraw
	}
	return nil
}

func (m *UnfreezeAction) GetTerminate() *UnfreezeTerminate {
	if x, ok := m.GetValue().(*UnfreezeAction_Terminate); ok {
		return x.Terminate
	}
	return nil
}

func (m *UnfreezeAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UnfreezeAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UnfreezeAction_OneofMarshaler, _UnfreezeAction_OneofUnmarshaler, _UnfreezeAction_OneofSizer, []interface{}{
		(*UnfreezeAction_Create)(nil),
		(*UnfreezeAction_Withdraw)(nil),
		(*UnfreezeAction_Terminate)(nil),
	}
}

func _UnfreezeAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UnfreezeAction)
	// value
	switch x := m.Value.(type) {
	case *UnfreezeAction_Create:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Create); err != nil {
			return err
		}
	case *UnfreezeAction_Withdraw:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Withdraw); err != nil {
			return err
		}
	case *UnfreezeAction_Terminate:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Terminate); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UnfreezeAction.Value has unexpected type %T", x)
	}
	return nil
}

func _UnfreezeAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UnfreezeAction)
	switch tag {
	case 1: // value.create
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UnfreezeCreate)
		err := b.DecodeMessage(msg)
		m.Value = &UnfreezeAction_Create{msg}
		return true, err
	case 2: // value.withdraw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UnfreezeWithdraw)
		err := b.DecodeMessage(msg)
		m.Value = &UnfreezeAction_Withdraw{msg}
		return true, err
	case 3: // value.terminate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UnfreezeTerminate)
		err := b.DecodeMessage(msg)
		m.Value = &UnfreezeAction_Terminate{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UnfreezeAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UnfreezeAction)
	// value
	switch x := m.Value.(type) {
	case *UnfreezeAction_Create:
		s := proto.Size(x.Create)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UnfreezeAction_Withdraw:
		s := proto.Size(x.Withdraw)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UnfreezeAction_Terminate:
		s := proto.Size(x.Terminate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// action
type UnfreezeCreate struct {
	StartTime   int64  `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	AssetExec   string `protobuf:"bytes,2,opt,name=assetExec,proto3" json:"assetExec,omitempty"`
	AssetSymbol string `protobuf:"bytes,3,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	TotalCount  int64  `protobuf:"varint,4,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Beneficiary string `protobuf:"bytes,5,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	Means       string `protobuf:"bytes,6,opt,name=means,proto3" json:"means,omitempty"`
	// Types that are valid to be assigned to MeansOpt:
	//	*UnfreezeCreate_FixAmount
	//	*UnfreezeCreate_LeftProportion
	//	*UnfreezeCreate_DecreaseAmount
	MeansOpt             isUnfreezeCreate_MeansOpt `protobuf_oneof:"meansOpt"`
	UnfreezeLabel        string                    `protobuf:"bytes,20,opt,name=unfreezeLabel,proto3" json:"unfreezeLabel,omitempty"`
	IsRevoke             bool                      `protobuf:"varint,21,opt,name=isRevoke,proto3" json:"isRevoke,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UnfreezeCreate) Reset()         { *m = UnfreezeCreate{} }
func (m *UnfreezeCreate) String() string { return proto.CompactTextString(m) }
func (*UnfreezeCreate) ProtoMessage()    {}
func (*UnfreezeCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{5}
}

func (m *UnfreezeCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfreezeCreate.Unmarshal(m, b)
}
func (m *UnfreezeCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfreezeCreate.Marshal(b, m, deterministic)
}
func (m *UnfreezeCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfreezeCreate.Merge(m, src)
}
func (m *UnfreezeCreate) XXX_Size() int {
	return xxx_messageInfo_UnfreezeCreate.Size(m)
}
func (m *UnfreezeCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfreezeCreate.DiscardUnknown(m)
}

var xxx_messageInfo_UnfreezeCreate proto.InternalMessageInfo

func (m *UnfreezeCreate) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *UnfreezeCreate) GetAssetExec() string {
	if m != nil {
		return m.AssetExec
	}
	return ""
}

func (m *UnfreezeCreate) GetAssetSymbol() string {
	if m != nil {
		return m.AssetSymbol
	}
	return ""
}

func (m *UnfreezeCreate) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *UnfreezeCreate) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func (m *UnfreezeCreate) GetMeans() string {
	if m != nil {
		return m.Means
	}
	return ""
}

type isUnfreezeCreate_MeansOpt interface {
	isUnfreezeCreate_MeansOpt()
}

type UnfreezeCreate_FixAmount struct {
	FixAmount *FixAmount `protobuf:"bytes,7,opt,name=fixAmount,proto3,oneof"`
}

type UnfreezeCreate_LeftProportion struct {
	LeftProportion *LeftProportion `protobuf:"bytes,8,opt,name=leftProportion,proto3,oneof"`
}

type UnfreezeCreate_DecreaseAmount struct {
	DecreaseAmount *DecreaseAmount `protobuf:"bytes,9,opt,name=decreaseAmount,proto3,oneof"`
}

func (*UnfreezeCreate_FixAmount) isUnfreezeCreate_MeansOpt() {}

func (*UnfreezeCreate_LeftProportion) isUnfreezeCreate_MeansOpt() {}

func (*UnfreezeCreate_DecreaseAmount) isUnfreezeCreate_MeansOpt() {}

func (m *UnfreezeCreate) GetMeansOpt() isUnfreezeCreate_MeansOpt {
	if m != nil {
		return m.MeansOpt
	}
	return nil
}

func (m *UnfreezeCreate) GetFixAmount() *FixAmount {
	if x, ok := m.GetMeansOpt().(*UnfreezeCreate_FixAmount); ok {
		return x.FixAmount
	}
	return nil
}

func (m *UnfreezeCreate) GetLeftProportion() *LeftProportion {
	if x, ok := m.GetMeansOpt().(*UnfreezeCreate_LeftProportion); ok {
		return x.LeftProportion
	}
	return nil
}

func (m *UnfreezeCreate) GetDecreaseAmount() *DecreaseAmount {
	if x, ok := m.GetMeansOpt().(*UnfreezeCreate_DecreaseAmount); ok {
		return x.DecreaseAmount
	}
	return nil
}

func (m *UnfreezeCreate) GetUnfreezeLabel() string {
	if m != nil {
		return m.UnfreezeLabel
	}
	return ""
}

func (m *UnfreezeCreate) GetIsRevoke() bool {
	if m != nil {
		return m.IsRevoke
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UnfreezeCreate) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UnfreezeCreate_OneofMarshaler, _UnfreezeCreate_OneofUnmarshaler, _UnfreezeCreate_OneofSizer, []interface{}{
		(*UnfreezeCreate_FixAmount)(nil),
		(*UnfreezeCreate_LeftProportion)(nil),
		(*UnfreezeCreate_DecreaseAmount)(nil),
	}
}

func _UnfreezeCreate_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UnfreezeCreate)
	// meansOpt
	switch x := m.MeansOpt.(type) {
	case *UnfreezeCreate_FixAmount:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FixAmount); err != nil {
			return err
		}
	case *UnfreezeCreate_LeftProportion:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LeftProportion); err != nil {
			return err
		}
	case *UnfreezeCreate_DecreaseAmount:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DecreaseAmount); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UnfreezeCreate.MeansOpt has unexpected type %T", x)
	}
	return nil
}

func _UnfreezeCreate_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UnfreezeCreate)
	switch tag {
	case 7: // meansOpt.fixAmount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FixAmount)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &UnfreezeCreate_FixAmount{msg}
		return true, err
	case 8: // meansOpt.leftProportion
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LeftProportion)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &UnfreezeCreate_LeftProportion{msg}
		return true, err
	case 9: // meansOpt.decreaseAmount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DecreaseAmount)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &UnfreezeCreate_DecreaseAmount{msg}
		return true, err
	default:
		return false, nil
	}
}

func _UnfreezeCreate_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UnfreezeCreate)
	// meansOpt
	switch x := m.MeansOpt.(type) {
	case *UnfreezeCreate_FixAmount:
		s := proto.Size(x.FixAmount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UnfreezeCreate_LeftProportion:
		s := proto.Size(x.LeftProportion)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *UnfreezeCreate_DecreaseAmount:
		s := proto.Size(x.DecreaseAmount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UnfreezeWithdraw struct {
	UnfreezeID           string   `protobuf:"bytes,1,opt,name=unfreezeID,proto3" json:"unfreezeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfreezeWithdraw) Reset()         { *m = UnfreezeWithdraw{} }
func (m *UnfreezeWithdraw) String() string { return proto.CompactTextString(m) }
func (*UnfreezeWithdraw) ProtoMessage()    {}
func (*UnfreezeWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{6}
}

func (m *UnfreezeWithdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfreezeWithdraw.Unmarshal(m, b)
}
func (m *UnfreezeWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfreezeWithdraw.Marshal(b, m, deterministic)
}
func (m *UnfreezeWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfreezeWithdraw.Merge(m, src)
}
func (m *UnfreezeWithdraw) XXX_Size() int {
	return xxx_messageInfo_UnfreezeWithdraw.Size(m)
}
func (m *UnfreezeWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfreezeWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_UnfreezeWithdraw proto.InternalMessageInfo

func (m *UnfreezeWithdraw) GetUnfreezeID() string {
	if m != nil {
		return m.UnfreezeID
	}
	return ""
}

type UnfreezeTerminate struct {
	UnfreezeID           string   `protobuf:"bytes,1,opt,name=unfreezeID,proto3" json:"unfreezeID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnfreezeTerminate) Reset()         { *m = UnfreezeTerminate{} }
func (m *UnfreezeTerminate) String() string { return proto.CompactTextString(m) }
func (*UnfreezeTerminate) ProtoMessage()    {}
func (*UnfreezeTerminate) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{7}
}

func (m *UnfreezeTerminate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfreezeTerminate.Unmarshal(m, b)
}
func (m *UnfreezeTerminate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfreezeTerminate.Marshal(b, m, deterministic)
}
func (m *UnfreezeTerminate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfreezeTerminate.Merge(m, src)
}
func (m *UnfreezeTerminate) XXX_Size() int {
	return xxx_messageInfo_UnfreezeTerminate.Size(m)
}
func (m *UnfreezeTerminate) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfreezeTerminate.DiscardUnknown(m)
}

var xxx_messageInfo_UnfreezeTerminate proto.InternalMessageInfo

func (m *UnfreezeTerminate) GetUnfreezeID() string {
	if m != nil {
		return m.UnfreezeID
	}
	return ""
}

// receipt
type ReceiptUnfreeze struct {
	Prev                 *Unfreeze `protobuf:"bytes,1,opt,name=prev,proto3" json:"prev,omitempty"`
	Current              *Unfreeze `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReceiptUnfreeze) Reset()         { *m = ReceiptUnfreeze{} }
func (m *ReceiptUnfreeze) String() string { return proto.CompactTextString(m) }
func (*ReceiptUnfreeze) ProtoMessage()    {}
func (*ReceiptUnfreeze) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{8}
}

func (m *ReceiptUnfreeze) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptUnfreeze.Unmarshal(m, b)
}
func (m *ReceiptUnfreeze) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptUnfreeze.Marshal(b, m, deterministic)
}
func (m *ReceiptUnfreeze) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptUnfreeze.Merge(m, src)
}
func (m *ReceiptUnfreeze) XXX_Size() int {
	return xxx_messageInfo_ReceiptUnfreeze.Size(m)
}
func (m *ReceiptUnfreeze) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptUnfreeze.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptUnfreeze proto.InternalMessageInfo

func (m *ReceiptUnfreeze) GetPrev() *Unfreeze {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *ReceiptUnfreeze) GetCurrent() *Unfreeze {
	if m != nil {
		return m.Current
	}
	return nil
}

type LocalUnfreeze struct {
	Unfreeze             *Unfreeze `protobuf:"bytes,1,opt,name=unfreeze,proto3" json:"unfreeze,omitempty"`
	TxIndex              string    `protobuf:"bytes,2,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	TerminateHeight      int64     `protobuf:"varint,3,opt,name=terminateHeight,proto3" json:"terminateHeight,omitempty"`
	TerminateTime        int64     `protobuf:"varint,4,opt,name=terminateTime,proto3" json:"terminateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LocalUnfreeze) Reset()         { *m = LocalUnfreeze{} }
func (m *LocalUnfreeze) String() string { return proto.CompactTextString(m) }
func (*LocalUnfreeze) ProtoMessage()    {}
func (*LocalUnfreeze) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{9}
}

func (m *LocalUnfreeze) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalUnfreeze.Unmarshal(m, b)
}
func (m *LocalUnfreeze) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalUnfreeze.Marshal(b, m, deterministic)
}
func (m *LocalUnfreeze) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalUnfreeze.Merge(m, src)
}
func (m *LocalUnfreeze) XXX_Size() int {
	return xxx_messageInfo_LocalUnfreeze.Size(m)
}
func (m *LocalUnfreeze) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalUnfreeze.DiscardUnknown(m)
}

var xxx_messageInfo_LocalUnfreeze proto.InternalMessageInfo

func (m *LocalUnfreeze) GetUnfreeze() *Unfreeze {
	if m != nil {
		return m.Unfreeze
	}
	return nil
}

func (m *LocalUnfreeze) GetTxIndex() string {
	if m != nil {
		return m.TxIndex
	}
	return ""
}

func (m *LocalUnfreeze) GetTerminateHeight() int64 {
	if m != nil {
		return m.TerminateHeight
	}
	return 0
}

func (m *LocalUnfreeze) GetTerminateTime() int64 {
	if m != nil {
		return m.TerminateTime
	}
	return 0
}

// query
type ReplyQueryUnfreezeWithdraw struct {
	UnfreezeID           string   `protobuf:"bytes,1,opt,name=unfreezeID,proto3" json:"unfreezeID,omitempty"`
	AvailableAmount      int64    `protobuf:"varint,2,opt,name=availableAmount,proto3" json:"availableAmount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyQueryUnfreezeWithdraw) Reset()         { *m = ReplyQueryUnfreezeWithdraw{} }
func (m *ReplyQueryUnfreezeWithdraw) String() string { return proto.CompactTextString(m) }
func (*ReplyQueryUnfreezeWithdraw) ProtoMessage()    {}
func (*ReplyQueryUnfreezeWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{10}
}

func (m *ReplyQueryUnfreezeWithdraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyQueryUnfreezeWithdraw.Unmarshal(m, b)
}
func (m *ReplyQueryUnfreezeWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyQueryUnfreezeWithdraw.Marshal(b, m, deterministic)
}
func (m *ReplyQueryUnfreezeWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyQueryUnfreezeWithdraw.Merge(m, src)
}
func (m *ReplyQueryUnfreezeWithdraw) XXX_Size() int {
	return xxx_messageInfo_ReplyQueryUnfreezeWithdraw.Size(m)
}
func (m *ReplyQueryUnfreezeWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyQueryUnfreezeWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyQueryUnfreezeWithdraw proto.InternalMessageInfo

func (m *ReplyQueryUnfreezeWithdraw) GetUnfreezeID() string {
	if m != nil {
		return m.UnfreezeID
	}
	return ""
}

func (m *ReplyQueryUnfreezeWithdraw) GetAvailableAmount() int64 {
	if m != nil {
		return m.AvailableAmount
	}
	return 0
}

type ReqUnfreezes struct {
	Direction            int32    `protobuf:"varint,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	FromKey              string   `protobuf:"bytes,3,opt,name=fromKey,proto3" json:"fromKey,omitempty"`
	Initiator            string   `protobuf:"bytes,4,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Beneficiary          string   `protobuf:"bytes,5,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUnfreezes) Reset()         { *m = ReqUnfreezes{} }
func (m *ReqUnfreezes) String() string { return proto.CompactTextString(m) }
func (*ReqUnfreezes) ProtoMessage()    {}
func (*ReqUnfreezes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{11}
}

func (m *ReqUnfreezes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUnfreezes.Unmarshal(m, b)
}
func (m *ReqUnfreezes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUnfreezes.Marshal(b, m, deterministic)
}
func (m *ReqUnfreezes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUnfreezes.Merge(m, src)
}
func (m *ReqUnfreezes) XXX_Size() int {
	return xxx_messageInfo_ReqUnfreezes.Size(m)
}
func (m *ReqUnfreezes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUnfreezes.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUnfreezes proto.InternalMessageInfo

func (m *ReqUnfreezes) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *ReqUnfreezes) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqUnfreezes) GetFromKey() string {
	if m != nil {
		return m.FromKey
	}
	return ""
}

func (m *ReqUnfreezes) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *ReqUnfreezes) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

type ReplyUnfreeze struct {
	//解冻交易ID（唯一识别码）
	UnfreezeID string `protobuf:"bytes,1,opt,name=unfreezeID,proto3" json:"unfreezeID,omitempty"`
	//开始时间
	StartTime int64 `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
	//币种
	AssetExec   string `protobuf:"bytes,3,opt,name=assetExec,proto3" json:"assetExec,omitempty"`
	AssetSymbol string `protobuf:"bytes,4,opt,name=assetSymbol,proto3" json:"assetSymbol,omitempty"`
	//冻结总额
	TotalCount int64 `protobuf:"varint,5,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	//发币人地址
	Initiator string `protobuf:"bytes,6,opt,name=initiator,proto3" json:"initiator,omitempty"`
	//收币人地址
	Beneficiary string `protobuf:"bytes,7,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	//解冻剩余币数
	Remaining int64 `protobuf:"varint,8,opt,name=remaining,proto3" json:"remaining,omitempty"`
	//解冻方式（百分比；固额;递减）
	Means string `protobuf:"bytes,9,opt,name=means,proto3" json:"means,omitempty"`
	// Types that are valid to be assigned to MeansOpt:
	//	*ReplyUnfreeze_FixAmount
	//	*ReplyUnfreeze_LeftProportion
	//	*ReplyUnfreeze_DecreaseAmount
	MeansOpt             isReplyUnfreeze_MeansOpt `protobuf_oneof:"meansOpt"`
	Terminated           bool                     `protobuf:"varint,20,opt,name=terminated,proto3" json:"terminated,omitempty"`
	Key                  string                   `protobuf:"bytes,21,opt,name=key,proto3" json:"key,omitempty"`
	UnfreezeLabel        string                   `protobuf:"bytes,22,opt,name=unfreezeLabel,proto3" json:"unfreezeLabel,omitempty"`
	TerminateTime        int64                    `protobuf:"varint,23,opt,name=terminateTime,proto3" json:"terminateTime,omitempty"`
	IsRevoke             bool                     `protobuf:"varint,24,opt,name=isRevoke,proto3" json:"isRevoke,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ReplyUnfreeze) Reset()         { *m = ReplyUnfreeze{} }
func (m *ReplyUnfreeze) String() string { return proto.CompactTextString(m) }
func (*ReplyUnfreeze) ProtoMessage()    {}
func (*ReplyUnfreeze) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{12}
}

func (m *ReplyUnfreeze) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUnfreeze.Unmarshal(m, b)
}
func (m *ReplyUnfreeze) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUnfreeze.Marshal(b, m, deterministic)
}
func (m *ReplyUnfreeze) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUnfreeze.Merge(m, src)
}
func (m *ReplyUnfreeze) XXX_Size() int {
	return xxx_messageInfo_ReplyUnfreeze.Size(m)
}
func (m *ReplyUnfreeze) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUnfreeze.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUnfreeze proto.InternalMessageInfo

func (m *ReplyUnfreeze) GetUnfreezeID() string {
	if m != nil {
		return m.UnfreezeID
	}
	return ""
}

func (m *ReplyUnfreeze) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ReplyUnfreeze) GetAssetExec() string {
	if m != nil {
		return m.AssetExec
	}
	return ""
}

func (m *ReplyUnfreeze) GetAssetSymbol() string {
	if m != nil {
		return m.AssetSymbol
	}
	return ""
}

func (m *ReplyUnfreeze) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ReplyUnfreeze) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *ReplyUnfreeze) GetBeneficiary() string {
	if m != nil {
		return m.Beneficiary
	}
	return ""
}

func (m *ReplyUnfreeze) GetRemaining() int64 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *ReplyUnfreeze) GetMeans() string {
	if m != nil {
		return m.Means
	}
	return ""
}

type isReplyUnfreeze_MeansOpt interface {
	isReplyUnfreeze_MeansOpt()
}

type ReplyUnfreeze_FixAmount struct {
	FixAmount *FixAmount `protobuf:"bytes,10,opt,name=fixAmount,proto3,oneof"`
}

type ReplyUnfreeze_LeftProportion struct {
	LeftProportion *LeftProportion `protobuf:"bytes,11,opt,name=leftProportion,proto3,oneof"`
}

type ReplyUnfreeze_DecreaseAmount struct {
	DecreaseAmount *DecreaseAmount `protobuf:"bytes,12,opt,name=decreaseAmount,proto3,oneof"`
}

func (*ReplyUnfreeze_FixAmount) isReplyUnfreeze_MeansOpt() {}

func (*ReplyUnfreeze_LeftProportion) isReplyUnfreeze_MeansOpt() {}

func (*ReplyUnfreeze_DecreaseAmount) isReplyUnfreeze_MeansOpt() {}

func (m *ReplyUnfreeze) GetMeansOpt() isReplyUnfreeze_MeansOpt {
	if m != nil {
		return m.MeansOpt
	}
	return nil
}

func (m *ReplyUnfreeze) GetFixAmount() *FixAmount {
	if x, ok := m.GetMeansOpt().(*ReplyUnfreeze_FixAmount); ok {
		return x.FixAmount
	}
	return nil
}

func (m *ReplyUnfreeze) GetLeftProportion() *LeftProportion {
	if x, ok := m.GetMeansOpt().(*ReplyUnfreeze_LeftProportion); ok {
		return x.LeftProportion
	}
	return nil
}

func (m *ReplyUnfreeze) GetDecreaseAmount() *DecreaseAmount {
	if x, ok := m.GetMeansOpt().(*ReplyUnfreeze_DecreaseAmount); ok {
		return x.DecreaseAmount
	}
	return nil
}

func (m *ReplyUnfreeze) GetTerminated() bool {
	if m != nil {
		return m.Terminated
	}
	return false
}

func (m *ReplyUnfreeze) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReplyUnfreeze) GetUnfreezeLabel() string {
	if m != nil {
		return m.UnfreezeLabel
	}
	return ""
}

func (m *ReplyUnfreeze) GetTerminateTime() int64 {
	if m != nil {
		return m.TerminateTime
	}
	return 0
}

func (m *ReplyUnfreeze) GetIsRevoke() bool {
	if m != nil {
		return m.IsRevoke
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReplyUnfreeze) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReplyUnfreeze_OneofMarshaler, _ReplyUnfreeze_OneofUnmarshaler, _ReplyUnfreeze_OneofSizer, []interface{}{
		(*ReplyUnfreeze_FixAmount)(nil),
		(*ReplyUnfreeze_LeftProportion)(nil),
		(*ReplyUnfreeze_DecreaseAmount)(nil),
	}
}

func _ReplyUnfreeze_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReplyUnfreeze)
	// meansOpt
	switch x := m.MeansOpt.(type) {
	case *ReplyUnfreeze_FixAmount:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FixAmount); err != nil {
			return err
		}
	case *ReplyUnfreeze_LeftProportion:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LeftProportion); err != nil {
			return err
		}
	case *ReplyUnfreeze_DecreaseAmount:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DecreaseAmount); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReplyUnfreeze.MeansOpt has unexpected type %T", x)
	}
	return nil
}

func _ReplyUnfreeze_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReplyUnfreeze)
	switch tag {
	case 10: // meansOpt.fixAmount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FixAmount)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &ReplyUnfreeze_FixAmount{msg}
		return true, err
	case 11: // meansOpt.leftProportion
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LeftProportion)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &ReplyUnfreeze_LeftProportion{msg}
		return true, err
	case 12: // meansOpt.decreaseAmount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DecreaseAmount)
		err := b.DecodeMessage(msg)
		m.MeansOpt = &ReplyUnfreeze_DecreaseAmount{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReplyUnfreeze_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReplyUnfreeze)
	// meansOpt
	switch x := m.MeansOpt.(type) {
	case *ReplyUnfreeze_FixAmount:
		s := proto.Size(x.FixAmount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReplyUnfreeze_LeftProportion:
		s := proto.Size(x.LeftProportion)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReplyUnfreeze_DecreaseAmount:
		s := proto.Size(x.DecreaseAmount)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ReplyUnfreezes struct {
	Unfreeze             []*ReplyUnfreeze `protobuf:"bytes,1,rep,name=unfreeze,proto3" json:"unfreeze,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReplyUnfreezes) Reset()         { *m = ReplyUnfreezes{} }
func (m *ReplyUnfreezes) String() string { return proto.CompactTextString(m) }
func (*ReplyUnfreezes) ProtoMessage()    {}
func (*ReplyUnfreezes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6caa0554cb0b9167, []int{13}
}

func (m *ReplyUnfreezes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyUnfreezes.Unmarshal(m, b)
}
func (m *ReplyUnfreezes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyUnfreezes.Marshal(b, m, deterministic)
}
func (m *ReplyUnfreezes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyUnfreezes.Merge(m, src)
}
func (m *ReplyUnfreezes) XXX_Size() int {
	return xxx_messageInfo_ReplyUnfreezes.Size(m)
}
func (m *ReplyUnfreezes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyUnfreezes.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyUnfreezes proto.InternalMessageInfo

func (m *ReplyUnfreezes) GetUnfreeze() []*ReplyUnfreeze {
	if m != nil {
		return m.Unfreeze
	}
	return nil
}

func init() {
	proto.RegisterType((*Unfreeze)(nil), "types.Unfreeze")
	proto.RegisterType((*FixAmount)(nil), "types.FixAmount")
	proto.RegisterType((*LeftProportion)(nil), "types.LeftProportion")
	proto.RegisterType((*DecreaseAmount)(nil), "types.DecreaseAmount")
	proto.RegisterType((*UnfreezeAction)(nil), "types.UnfreezeAction")
	proto.RegisterType((*UnfreezeCreate)(nil), "types.UnfreezeCreate")
	proto.RegisterType((*UnfreezeWithdraw)(nil), "types.UnfreezeWithdraw")
	proto.RegisterType((*UnfreezeTerminate)(nil), "types.UnfreezeTerminate")
	proto.RegisterType((*ReceiptUnfreeze)(nil), "types.ReceiptUnfreeze")
	proto.RegisterType((*LocalUnfreeze)(nil), "types.LocalUnfreeze")
	proto.RegisterType((*ReplyQueryUnfreezeWithdraw)(nil), "types.ReplyQueryUnfreezeWithdraw")
	proto.RegisterType((*ReqUnfreezes)(nil), "types.ReqUnfreezes")
	proto.RegisterType((*ReplyUnfreeze)(nil), "types.ReplyUnfreeze")
	proto.RegisterType((*ReplyUnfreezes)(nil), "types.ReplyUnfreezes")
}

func init() { proto.RegisterFile("unfreeze.proto", fileDescriptor_6caa0554cb0b9167) }

var fileDescriptor_6caa0554cb0b9167 = []byte{
	// 909 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xf7, 0xc5, 0xff, 0xc7, 0xb1, 0x13, 0xb6, 0x49, 0x7a, 0x8a, 0x10, 0x32, 0x47, 0x85, 0x8c,
	0x90, 0x42, 0xe5, 0x82, 0x84, 0xc4, 0x03, 0x6a, 0x5a, 0xc0, 0x15, 0x51, 0x29, 0xdb, 0x20, 0x9e,
	0xd7, 0xe7, 0x71, 0xb2, 0xea, 0xfd, 0x71, 0xf7, 0xd6, 0x69, 0x8e, 0x0f, 0xc1, 0x27, 0xe0, 0x99,
	0x8f, 0xc1, 0x33, 0x12, 0x7c, 0x23, 0x5e, 0xd0, 0xee, 0xed, 0xdd, 0x79, 0xcf, 0x4e, 0xac, 0x92,
	0x47, 0xfa, 0x96, 0xf9, 0xcd, 0xcc, 0x6f, 0x77, 0xc6, 0x33, 0xbf, 0xbd, 0xc0, 0x60, 0x19, 0xcd,
	0x05, 0xe2, 0x2f, 0x78, 0xb2, 0x10, 0xb1, 0x8c, 0x49, 0x53, 0xa6, 0x0b, 0x4c, 0x8e, 0x77, 0xfd,
	0x38, 0x0c, 0xe3, 0x28, 0x03, 0xbd, 0x3f, 0x1a, 0xd0, 0xf9, 0xc9, 0xc4, 0x91, 0x0f, 0x00, 0xf2,
	0x9c, 0x67, 0x4f, 0x5d, 0x67, 0xe8, 0x8c, 0xba, 0x74, 0x05, 0x21, 0xef, 0x43, 0x37, 0x91, 0x4c,
	0xc8, 0x73, 0x1e, 0xa2, 0xbb, 0x33, 0x74, 0x46, 0x75, 0x5a, 0x02, 0xca, 0xcb, 0x92, 0x04, 0xe5,
	0x37, 0xd7, 0xe8, 0xbb, 0x75, 0x9d, 0x5c, 0x02, 0x64, 0x08, 0x3d, 0x6d, 0xbc, 0x4c, 0xc3, 0x69,
	0x1c, 0xb8, 0x0d, 0xed, 0x5f, 0x85, 0xd4, 0xe9, 0x32, 0x96, 0x2c, 0x78, 0x12, 0x2f, 0x23, 0xe9,
	0x36, 0x35, 0xfd, 0x0a, 0xa2, 0xf8, 0x79, 0xc4, 0x25, 0x67, 0x32, 0x16, 0x6e, 0x2b, 0xe3, 0x2f,
	0x00, 0xc5, 0x3f, 0xc5, 0x08, 0xe7, 0xdc, 0xe7, 0x4c, 0xa4, 0x6e, 0x3b, 0xe3, 0x5f, 0x81, 0x54,
	0xbe, 0xc0, 0x90, 0xf1, 0x88, 0x47, 0x17, 0x6e, 0x27, 0xbb, 0x7d, 0x01, 0x90, 0x03, 0x68, 0x86,
	0xc8, 0xa2, 0xc4, 0xed, 0xea, 0xcc, 0xcc, 0x20, 0x0f, 0xa1, 0x3b, 0xe7, 0xd7, 0x8f, 0x43, 0x7d,
	0x25, 0x18, 0x3a, 0xa3, 0xde, 0x78, 0xff, 0x44, 0xf7, 0xf1, 0xe4, 0xdb, 0x1c, 0x9f, 0xd4, 0x68,
	0x19, 0x44, 0xbe, 0x86, 0x41, 0x80, 0x73, 0xf9, 0x42, 0xc4, 0x8b, 0x58, 0x48, 0x1e, 0x47, 0x6e,
	0x4f, 0xa7, 0x1d, 0x9a, 0xb4, 0x33, 0xcb, 0x39, 0xa9, 0xd1, 0x4a, 0xb8, 0x22, 0x98, 0xa1, 0x2f,
	0x90, 0x25, 0x68, 0xce, 0xdd, 0xb5, 0x08, 0x9e, 0x5a, 0x4e, 0x45, 0x60, 0x87, 0xeb, 0x3e, 0xa2,
	0x08, 0x79, 0xc4, 0x24, 0xce, 0xdc, 0x83, 0xa1, 0x33, 0xea, 0xd0, 0x15, 0x84, 0x3c, 0x80, 0x7e,
	0xfe, 0x9b, 0x9e, 0xb1, 0x29, 0x06, 0xee, 0xa1, 0xae, 0xd8, 0x06, 0xc9, 0x31, 0x74, 0x78, 0x42,
	0xf1, 0x2a, 0x7e, 0x85, 0xee, 0x91, 0xe6, 0x28, 0xec, 0x53, 0x80, 0x8e, 0x6e, 0xcf, 0x0f, 0x0b,
	0xe9, 0x7d, 0x05, 0xdd, 0xa2, 0x13, 0xe4, 0x08, 0x5a, 0x0b, 0x14, 0x3c, 0x9e, 0xe9, 0xe1, 0xa9,
	0x53, 0x63, 0x29, 0x9c, 0x65, 0xb5, 0x64, 0x53, 0x63, 0x2c, 0xef, 0x39, 0x0c, 0xec, 0x7e, 0xdc,
	0xc8, 0xf0, 0x00, 0xfa, 0x12, 0xa3, 0xf3, 0xcb, 0x78, 0x99, 0xb0, 0x68, 0x26, 0x2f, 0x0d, 0x91,
	0x0d, 0x7a, 0x7f, 0x3b, 0x30, 0xb0, 0xfb, 0x73, 0x37, 0x42, 0xf2, 0x10, 0xee, 0xcd, 0xb9, 0x48,
	0xa4, 0x4d, 0xaa, 0xa7, 0xbb, 0x4e, 0x37, 0xb9, 0xc8, 0xc7, 0xe5, 0xcf, 0xf7, 0x22, 0x3b, 0xb7,
	0xa1, 0x83, 0x2b, 0x28, 0xf1, 0x60, 0x37, 0x47, 0x9e, 0x2f, 0xc3, 0xc4, 0xcc, 0xbb, 0x85, 0x79,
	0x7f, 0x39, 0x30, 0xc8, 0x97, 0xf3, 0xb1, 0xaf, 0xfb, 0xf3, 0x19, 0xb4, 0x54, 0x80, 0x44, 0x5d,
	0x4e, 0x39, 0x15, 0x79, 0xd8, 0x13, 0xed, 0x9c, 0xd4, 0xa8, 0x09, 0x23, 0x5f, 0x40, 0xe7, 0x0d,
	0x97, 0x97, 0x33, 0xc1, 0xde, 0xe8, 0x12, 0x7b, 0xe3, 0xfb, 0x95, 0x94, 0x9f, 0x8d, 0x7b, 0x52,
	0xa3, 0x45, 0x28, 0xf9, 0x12, 0xba, 0xc5, 0xc8, 0xe8, 0x72, 0x7b, 0x63, 0xb7, 0x92, 0x77, 0x9e,
	0xfb, 0xd5, 0x02, 0x14, 0xc1, 0x64, 0x00, 0x3b, 0x32, 0xd5, 0x45, 0x37, 0xe9, 0x8e, 0x4c, 0x4f,
	0xdb, 0xd0, 0xbc, 0x62, 0xc1, 0x12, 0xbd, 0x3f, 0xeb, 0x65, 0x35, 0xd9, 0x35, 0x6d, 0x41, 0x71,
	0x6e, 0x15, 0x94, 0x9d, 0x2d, 0x82, 0x52, 0xdf, 0x26, 0x28, 0x8d, 0x35, 0x41, 0xa9, 0x48, 0x46,
	0x73, 0x5d, 0x32, 0x0a, 0x51, 0x68, 0xdd, 0x28, 0x0a, 0xed, 0xff, 0x26, 0x0a, 0x9d, 0xbb, 0x8a,
	0x42, 0xf7, 0xed, 0x44, 0x61, 0x6d, 0xe9, 0x0f, 0xb6, 0x2d, 0xfd, 0xe1, 0x2d, 0x4b, 0x3f, 0x86,
	0xfd, 0xea, 0xf4, 0x6c, 0x7b, 0x3c, 0xbc, 0x47, 0xf0, 0xde, 0xda, 0xe4, 0x6c, 0x4d, 0x62, 0xb0,
	0x47, 0xd1, 0x47, 0xbe, 0x90, 0xc5, 0x23, 0xf5, 0x11, 0x34, 0x16, 0x02, 0xaf, 0xcc, 0xfc, 0xef,
	0x55, 0x86, 0x92, 0x6a, 0x27, 0xf9, 0x04, 0xda, 0xfe, 0x52, 0x08, 0x34, 0x8a, 0xb3, 0x21, 0x2e,
	0xf7, 0x7b, 0xbf, 0x3b, 0xd0, 0x3f, 0x8b, 0x7d, 0x16, 0x14, 0x27, 0x7c, 0x0a, 0x9d, 0xfc, 0x0a,
	0x37, 0x9d, 0x52, 0x04, 0x10, 0x17, 0xda, 0xf2, 0xfa, 0x59, 0x34, 0xc3, 0x6b, 0x33, 0xa2, 0xb9,
	0x49, 0x46, 0xb0, 0x57, 0x6c, 0xc5, 0x04, 0xf9, 0xc5, 0x65, 0xae, 0x1b, 0x55, 0x38, 0xd3, 0x22,
	0x03, 0xe9, 0x55, 0x68, 0xe4, 0x5a, 0xb4, 0x02, 0x7a, 0x73, 0x38, 0xa6, 0xb8, 0x08, 0xd2, 0x1f,
	0x97, 0x28, 0xd2, 0xb7, 0x6d, 0xbf, 0xba, 0x0d, 0xbb, 0x62, 0x3c, 0x60, 0xd3, 0x20, 0x1f, 0xa1,
	0x4c, 0xf1, 0xaa, 0xb0, 0xf7, 0x9b, 0x03, 0xbb, 0x14, 0x5f, 0xe7, 0x27, 0x24, 0x6a, 0x0f, 0x67,
	0x5c, 0xa0, 0x16, 0x20, 0xcd, 0xdc, 0xa4, 0x25, 0xa0, 0x76, 0xc4, 0x2f, 0xe8, 0x9a, 0x34, 0x33,
	0x54, 0x5b, 0xe6, 0x22, 0x0e, 0xbf, 0xc7, 0xd4, 0x6c, 0x66, 0x6e, 0xda, 0xcf, 0x78, 0x63, 0xcb,
	0x33, 0xbe, 0xbe, 0x93, 0xde, 0x3f, 0x0d, 0xe8, 0xeb, 0x3e, 0xbc, 0xfb, 0x6c, 0xf9, 0x5f, 0x7d,
	0xb6, 0xec, 0x43, 0xfd, 0x15, 0xa6, 0xe6, 0x63, 0x45, 0xfd, 0xb9, 0xae, 0x69, 0x47, 0x9b, 0x34,
	0x6d, 0x6d, 0xb9, 0xee, 0x6f, 0x58, 0x2e, 0x4b, 0xf9, 0xdc, 0x5b, 0x94, 0xef, 0x14, 0x06, 0xd6,
	0xf0, 0xa9, 0x5e, 0xaf, 0xaa, 0x45, 0x7d, 0xd4, 0x1b, 0x1f, 0x98, 0x92, 0xad, 0xc0, 0x52, 0x32,
	0xc6, 0xbf, 0x3a, 0x65, 0x0a, 0x39, 0x83, 0x7b, 0xdf, 0xa1, 0x5c, 0x5b, 0xe7, 0xfd, 0x82, 0xe3,
	0xf5, 0x4b, 0x29, 0x78, 0x74, 0x71, 0xfc, 0xe1, 0x2a, 0xeb, 0x46, 0x0d, 0xf0, 0x6a, 0xe4, 0x73,
	0xe8, 0x5b, 0xae, 0x0d, 0x3c, 0x55, 0x2d, 0xf3, 0x6a, 0xd3, 0x96, 0xfe, 0x5f, 0xe0, 0xd1, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0x5d, 0x30, 0x8f, 0x32, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UnfreezeClient is the client API for Unfreeze service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UnfreezeClient interface {
	GetUnfreezeWithdraw(ctx context.Context, in *types.ReqString, opts ...grpc.CallOption) (*ReplyQueryUnfreezeWithdraw, error)
	QueryUnfreeze(ctx context.Context, in *types.ReqString, opts ...grpc.CallOption) (*Unfreeze, error)
}

type unfreezeClient struct {
	cc *grpc.ClientConn
}

func NewUnfreezeClient(cc *grpc.ClientConn) UnfreezeClient {
	return &unfreezeClient{cc}
}

func (c *unfreezeClient) GetUnfreezeWithdraw(ctx context.Context, in *types.ReqString, opts ...grpc.CallOption) (*ReplyQueryUnfreezeWithdraw, error) {
	out := new(ReplyQueryUnfreezeWithdraw)
	err := c.cc.Invoke(ctx, "/types.unfreeze/GetUnfreezeWithdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unfreezeClient) QueryUnfreeze(ctx context.Context, in *types.ReqString, opts ...grpc.CallOption) (*Unfreeze, error) {
	out := new(Unfreeze)
	err := c.cc.Invoke(ctx, "/types.unfreeze/QueryUnfreeze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnfreezeServer is the server API for Unfreeze service.
type UnfreezeServer interface {
	GetUnfreezeWithdraw(context.Context, *types.ReqString) (*ReplyQueryUnfreezeWithdraw, error)
	QueryUnfreeze(context.Context, *types.ReqString) (*Unfreeze, error)
}

func RegisterUnfreezeServer(s *grpc.Server, srv UnfreezeServer) {
	s.RegisterService(&_Unfreeze_serviceDesc, srv)
}

func _Unfreeze_GetUnfreezeWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnfreezeServer).GetUnfreezeWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.unfreeze/GetUnfreezeWithdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnfreezeServer).GetUnfreezeWithdraw(ctx, req.(*types.ReqString))
	}
	return interceptor(ctx, in, info, handler)
}

func _Unfreeze_QueryUnfreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.ReqString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnfreezeServer).QueryUnfreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.unfreeze/QueryUnfreeze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnfreezeServer).QueryUnfreeze(ctx, req.(*types.ReqString))
	}
	return interceptor(ctx, in, info, handler)
}

var _Unfreeze_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.unfreeze",
	HandlerType: (*UnfreezeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUnfreezeWithdraw",
			Handler:    _Unfreeze_GetUnfreezeWithdraw_Handler,
		},
		{
			MethodName: "QueryUnfreeze",
			Handler:    _Unfreeze_QueryUnfreeze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "unfreeze.proto",
}
